spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blog-system
    username: postgres
    password: postgres
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    open-in-view: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.blog.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
